### ISSUE TITLE
log-x option for visualization

### ISSUE THREAD

**Issue by mhance** [alexander-held/cabinetry#178]
Really enjoying using cabinetry with my undergrads.  One minor thing that I ran into was trying to plot a discriminant that drops sharply near zero.  I'd like to plot that on a log-x scale.  This is pretty niche, and I don't think we'd ever want automatic log-x switching, but enabling it via a function argument for `data_MC` and `data_MC_from_histograms` would be great.  Thanks!

**Comment by alexander-held** [comment]
Glad to hear that, and thank you for the suggestion! The next `cabinetry` release 0.1.8 will have this implemented via a `log_scale_x` keyword argument.

In the longer term, the plotting code will evolve to make it possible for users to set such properties themselves (see also discussion in #113).

**Comment by mhance** [comment]
Great, thanks a lot Alex!  This all sounds great.  I'll keep an eye out for 0.1.8.

**Comment by alexander-held** [comment]
`cabinetry` [v0.1.8](https://github.com/alexander-held/cabinetry/releases/tag/v0.1.8) has been released and is available via pypi: https://pypi.org/project/cabinetry/0.1.8/.
